# Generated by Django 6.0.2 on 2026-03-02 09:33

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Claim',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('claim_type', models.CharField(choices=[('IMAGE', 'Image'), ('VIDEO', 'Video'), ('URL', 'URL'), ('FILE', 'File')], max_length=20)),
                ('media_url', models.CharField(blank=True, max_length=500, null=True)),
                ('media_hash', models.CharField(blank=True, max_length=64, null=True)),
                ('url_link', models.URLField(blank=True, max_length=500, null=True)),
                ('context_text', models.TextField(blank=True, null=True)),
                ('ai_summary', models.TextField(blank=True, null=True)),
                ('verdict', models.CharField(blank=True, max_length=20, null=True)),
                ('consensus_score', models.FloatField(blank=True, null=True)),
                ('verified_via', models.CharField(choices=[('AI_EXTENSION', 'AI Extension'), ('COMMUNITY', 'Community Platform'), ('PENDING', 'Pending')], default='PENDING', max_length=20)),
                ('last_updated', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Thread',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('caption', models.TextField(blank=True, null=True)),
                ('status', models.CharField(blank=True, max_length=20, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='threads', to=settings.AUTH_USER_MODEL)),
                ('claim', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='threads', to='api.claim')),
            ],
        ),
        migrations.CreateModel(
            name='EvidenceSubmission',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('evidence_caption', models.TextField(blank=True, null=True)),
                ('evidence_url', models.URLField(blank=True, max_length=500, null=True)),
                ('evidence_type', models.CharField(blank=True, choices=[('IMAGE', 'Image'), ('URL_LINK', 'URL Link')], max_length=20, null=True)),
                ('contributor_trust_snapshot', models.FloatField(blank=True, null=True)),
                ('submitted_at', models.DateTimeField(auto_now_add=True)),
                ('contributor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='evidence_submissions', to=settings.AUTH_USER_MODEL)),
                ('thread', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='evidence_submissions', to='api.thread')),
            ],
        ),
        migrations.CreateModel(
            name='ThreadComment',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('comment_text', models.TextField()),
                ('commented_at', models.DateTimeField(auto_now_add=True)),
                ('commenter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to=settings.AUTH_USER_MODEL)),
                ('thread', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='api.thread')),
            ],
        ),
        migrations.CreateModel(
            name='Vote',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('vote_value', models.BooleanField()),
                ('vote_trust_snapshot', models.FloatField(blank=True, null=True)),
                ('voted_at', models.DateTimeField(auto_now_add=True)),
                ('evidence', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='votes', to='api.evidencesubmission')),
                ('voter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='votes', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
