# Generated by Django 6.0.2 on 2026-03-03 02:20

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_consumptionlog'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('trust_score', models.FloatField(default=0.0)),
                ('bio', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='consumptionlog',
            name='claim',
        ),
        migrations.RemoveField(
            model_name='consumptionlog',
            name='user',
        ),
        migrations.AddConstraint(
            model_name='vote',
            constraint=models.UniqueConstraint(fields=('evidence', 'voter'), name='unique_vote_per_evidence_per_user'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL),
        ),
        migrations.DeleteModel(
            name='ConsumptionLog',
        ),
    ]
