# Generated by Django 6.0.2 on 2026-03-10 13:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_claim_source_link_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='claim',
            name='source_type',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
