# Generated by Django 6.0.2 on 2026-03-15 11:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_claim_source_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='thread',
            name='status',
            field=models.CharField(blank=True, default='OPEN', max_length=20, null=True),
        ),
    ]
