# Generated by Django 6.0.2 on 2026-03-15 13:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_alter_thread_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='thread',
            name='flag_reason',
            field=models.CharField(blank=True, choices=[('FACT', 'Fact'), ('FAKE', 'Fake'), ('MISLEADING', 'Misleading'), ('SATIRE', 'Satire'), ('UNVERIFIED', 'Unverified')], max_length=20, null=True),
        ),
    ]
