# Generated by Django 6.0.2 on 2026-03-15 14:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_thread_flag_reason'),
    ]

    operations = [
        migrations.AddField(
            model_name='claim',
            name='top_verdict_source',
            field=models.URLField(blank=True, max_length=500, null=True),
        ),
    ]
