# Generated by Django 6.0.2 on 2026-03-17 12:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_claim_top_verdict_source'),
    ]

    operations = [
        migrations.AlterField(
            model_name='threadcomment',
            name='comment_text',
            field=models.TextField(blank=True, null=True),
        ),
    ]
