# Generated by Django 6.0.2 on 2026-03-18 15:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0009_alter_threadcomment_comment_text'),
    ]

    operations = [
        migrations.AddField(
            model_name='claim',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='claims/images/'),
        ),
    ]
