# Generated by Django 6.0.2 on 2026-03-23 14:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0011_userprofile_email_verification_token_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='evidencesubmission',
            name='evidence_verdict',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='evidencesubmission',
            name='evidence_type',
            field=models.CharField(blank=True, choices=[('CONTRADICTS CLAIM', 'Contradicts Claim'), ('SUPPORTS CLAIM', 'Supports Claim'), ('PROVIDES CONTEXT', 'Provides Context'), ('SOURCE VERIFICATION', 'Source Verification')], max_length=20, null=True),
        ),
    ]
