# Generated by Django 6.0.2 on 2026-03-24 05:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0012_evidencesubmission_evidence_verdict_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='evidencesubmission',
            name='evidence_status',
            field=models.CharField(blank=True, default='PENDING', max_length=20, null=True),
        ),
    ]
