# Generated by Django 6.0.2 on 2026-03-24 06:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0013_evidencesubmission_evidence_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='evidencesubmission',
            name='evidence_status',
            field=models.CharField(choices=[('UNVERIFIED', 'Unverified'), ('VERIFIED', 'Verified'), ('REJECTED', 'Rejected')], default='UNVERIFIED', max_length=20),
        ),
    ]
