# Generated by Django 6.0.2 on 2026-03-24 15:36

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0014_alter_evidencesubmission_evidence_status'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='thread',
            name='moderated_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='thread',
            name='moderated_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='moderated_threads', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='thread',
            name='moderator_notes',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='thread',
            name='moderator_verdict',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='role',
            field=models.CharField(choices=[('USER', 'User'), ('MODERATOR', 'Moderator')], default='USER', max_length=20),
        ),
        migrations.CreateModel(
            name='ThreadFlag',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('reason', models.CharField(choices=[('INAPPROPRIATE', 'Inappropriate Content'), ('SPAM', 'Spam'), ('HARASSMENT', 'Harassment'), ('OTHER', 'Other')], max_length=20)),
                ('notes', models.TextField(blank=True, null=True)),
                ('flagged_at', models.DateTimeField(auto_now_add=True)),
                ('flagged_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='thread_flags', to=settings.AUTH_USER_MODEL)),
                ('thread', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='flags', to='api.thread')),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('thread', 'flagged_by'), name='unique_flag_per_thread_per_user')],
            },
        ),
    ]
