# Generated by Django 6.0.2 on 2026-03-25 13:53

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0016_claim_ai_verdict_claim_final_verdict'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='evidencesubmission',
            name='moderator_notes',
            field=models.TextField(blank=True, help_text='Notes from moderator why evidence was verified/rejected', null=True),
        ),
        migrations.AddField(
            model_name='evidencesubmission',
            name='verified_at',
            field=models.DateTimeField(blank=True, help_text='Timestamp when evidence was verified by moderator', null=True),
        ),
        migrations.AddField(
            model_name='evidencesubmission',
            name='verified_by',
            field=models.ForeignKey(blank=True, help_text='Moderator who verified this evidence', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='verified_evidence', to=settings.AUTH_USER_MODEL),
        ),
    ]
