# Generated by Django 6.0.2 on 2026-03-27 21:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0017_evidencesubmission_moderator_notes_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='claim',
            name='is_ai_generated',
            field=models.BooleanField(default=False),
        ),
    ]
