# Generated by Django 6.0.2 on 2026-04-04 13:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0019_merge_0018_and_trust_baseline'),
    ]

    operations = [
        migrations.AddField(
            model_name='claim',
            name='claim_fingerprint',
            field=models.CharField(blank=True, db_index=True, help_text='Canonical fingerprint for deduplication (pHash for images, normalized URL hash, or text hash)', max_length=128, null=True),
        ),
    ]
