# Generated by Django 5.1.15 on 2026-04-05 19:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0020_add_claim_fingerprint'),
    ]

    operations = [
        migrations.AddField(
            model_name='claim',
            name='score_context',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
