# Generated by Django 6.0.2 on 2026-04-06 01:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0021_add_claim_embedding'),
        ('api', '0021_claim_score_context'),
    ]

    operations = [
    ]
