# Generated by Django 5.1.15 on 2026-04-06 06:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0021_claim_score_context'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='thread',
            name='flag_reason',
        ),
    ]
