# Generated by Django 6.0.2 on 2026-04-06 01:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0022_merge_20260406_0901'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='claim',
            name='claim_embedding_hnsw_idx',
        ),
        migrations.RemoveField(
            model_name='thread',
            name='flag_reason',
        ),
        migrations.AddField(
            model_name='thread',
            name='escalation_reason',
            field=models.CharField(blank=True, choices=[('INCORRECT_VERDICT', 'AI gave an incorrect or unverified verdict'), ('LOW_CONFIDENCE', 'AI confidence score is too low'), ('MISSING_CONTEXT', 'The context provided is incomplete or missing'), ('OUTDATED_INFO', 'The AI relied on outdated information or news'), ('OTHER', 'Other')], max_length=20, null=True),
        ),
    ]
