# Generated by Django 6.0.2 on 2026-04-06 01:03

import pgvector.django.indexes
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0023_remove_claim_claim_embedding_hnsw_idx_and_more'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='claim',
            index=pgvector.django.indexes.HnswIndex(ef_construction=64, fields=['claim_embedding'], m=16, name='claim_embedding_hnsw_idx', opclasses=['vector_cosine_ops']),
        ),
    ]
