# Generated by Django 6.0.2 on 2026-04-06 10:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0022_remove_thread_flag_reason'),
        ('api', '0024_claim_claim_embedding_hnsw_idx'),
    ]

    operations = [
    ]
