# Generated by Django 6.0.2 on 2026-04-19 16:21

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0027_userprofile_avatar_url'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='fact_check_points',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.CreateModel(
            name='ClaimCheckHistory',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('checked_at', models.DateTimeField(auto_now_add=True)),
                ('claim', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='check_history', to='api.claim')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='claim_check_history', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-checked_at'],
            },
        ),
    ]
