# Generated by Django 5.1.15 on 2026-04-19 19:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0028_userprofile_fact_check_points_claimcheckhistory'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='saved_claims',
            field=models.ManyToManyField(blank=True, related_name='saved_by_users', to='api.claim'),
        ),
    ]
