# Generated by Django 6.0.2 on 2026-04-20 08:56

from django.db import migrations, models


def migrate_moderator_role_forward(apps, schema_editor):
    UserProfile = apps.get_model("api", "UserProfile")
    UserProfile.objects.filter(role="MODERATOR").update(role="MOD")


def migrate_moderator_role_backward(apps, schema_editor):
    UserProfile = apps.get_model("api", "UserProfile")
    UserProfile.objects.filter(role="MOD").update(role="MODERATOR")


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0029_userprofile_saved_claims'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='organization_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='role',
            field=models.CharField(choices=[('USER', 'User'), ('MOD', 'Moderator')], default='USER', max_length=20),
        ),
        migrations.RunPython(migrate_moderator_role_forward, migrate_moderator_role_backward),
    ]
