# Generated by Django 5.1.15 on 2026-04-20 20:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0030_userprofile_organization_name_alter_userprofile_role'),
    ]

    operations = [
        migrations.AddField(
            model_name='claim',
            name='ai_sources',
            field=models.JSONField(blank=True, default=list, null=True),
        ),
    ]
