# Generated by Django 5.1.15 on 2026-04-21 03:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0031_claim_ai_sources'),
    ]

    operations = [
        migrations.AddField(
            model_name='claim',
            name='ai_reasoning',
            field=models.TextField(blank=True, null=True),
        ),
    ]
