# Generated by Django 6.0.2 on 2026-04-21 16:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0032_claim_ai_reasoning'),
    ]

    operations = [
        migrations.AlterField(
            model_name='claim',
            name='claim_type',
            field=models.CharField(choices=[('TEXT', 'Text'), ('IMAGE', 'Image'), ('VIDEO', 'Video'), ('URL', 'URL'), ('FILE', 'File')], default='TEXT', max_length=20),
        ),
    ]
