# Generated by Django 6.0.2 on 2026-04-22 00:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0033_alter_claim_claim_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='thread',
            name='display_id',
            field=models.PositiveIntegerField(editable=False, null=True, unique=True),
        ),
    ]
