# Generated by Django 5.1.15 on 2026-04-27 04:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0034_thread_display_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='claim',
            name='media_url',
            field=models.CharField(blank=True, max_length=2000, null=True),
        ),
        migrations.AlterField(
            model_name='claim',
            name='source_link',
            field=models.URLField(blank=True, max_length=2000, null=True),
        ),
        migrations.AlterField(
            model_name='claim',
            name='top_verdict_source',
            field=models.URLField(blank=True, max_length=2000, null=True),
        ),
        migrations.AlterField(
            model_name='claim',
            name='url_link',
            field=models.URLField(blank=True, max_length=2000, null=True),
        ),
    ]
