# Generated by Django 5.1.15 on 2026-04-30 17:39

import django.contrib.postgres.indexes
import django.contrib.postgres.search
import django.db.models.deletion
import pgvector.django.indexes
import pgvector.django.vector
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0035_alter_claim_media_url_alter_claim_source_link_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='OfficialFactCheck',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('canonical_claim', models.TextField(help_text="A clean, third-person statement of the rumor (e.g., 'The Pope wore a white puffer jacket.')")),
                ('verdict', models.CharField(max_length=20)),
                ('summary', models.TextField(help_text='The official explanation approved by a moderator.')),
                ('sources', models.JSONField(blank=True, default=list, help_text='List of verified URL strings.')),
                ('embedding', pgvector.django.vector.VectorField(blank=True, dimensions=384, help_text='Sentence transformer embedding for Semantic Search', null=True)),
                ('search_vector', django.contrib.postgres.search.SearchVectorField(blank=True, help_text='PostgreSQL tsvector for BM25 Keyword Search', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('published_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='published_fact_checks', to=settings.AUTH_USER_MODEL)),
                ('source_thread', models.ForeignKey(blank=True, help_text='Links back to the community thread if auto-published.', null=True, on_delete=django.db.models.deletion.SET_NULL, to='api.thread')),
            ],
            options={
                'indexes': [pgvector.django.indexes.HnswIndex(ef_construction=64, fields=['embedding'], m=16, name='official_claim_hnsw_idx', opclasses=['vector_cosine_ops']), django.contrib.postgres.indexes.GinIndex(fields=['search_vector'], name='official_claim_gin_idx')],
            },
        ),
    ]
