# Generated by Django 6.0.2 on 2026-06-20 02:42

import pgvector.django.indexes
from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0036_officialfactcheck'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='claim',
            name='claim_embedding_hnsw_idx',
        ),
        migrations.RemoveIndex(
            model_name='officialfactcheck',
            name='official_claim_hnsw_idx',
        ),
        migrations.AddIndex(
            model_name='claim',
            index=pgvector.django.indexes.HnswIndex(ef_construction=128, fields=['claim_embedding'], m=16, name='claim_embedding_hnsw_idx', opclasses=['vector_cosine_ops']),
        ),
        migrations.AddIndex(
            model_name='officialfactcheck',
            index=pgvector.django.indexes.HnswIndex(ef_construction=128, fields=['embedding'], m=16, name='official_claim_hnsw_idx', opclasses=['vector_cosine_ops']),
        ),
        migrations.RemoveField(
            model_name='claim',
            name='verdict',
        ),
    ]
