# Generated by Django 6.0.2 on 2026-08-23 02:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0037_remove_claim_claim_embedding_hnsw_idx_and_more'),
    ]

    operations = [
        migrations.AddField(
        model_name="userprofile",
        name="has_completed_onboarding",
        field=models.BooleanField(default=True),
    ),

        migrations.AlterField(
            model_name="userprofile",
            name="has_completed_onboarding",
            field=models.BooleanField(default=False),
        ),
    ]
