# Generated by Django 5.1.15 on 2026-08-23 19:17

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0038_userprofile_has_completed_onboarding'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CanonicalSource',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('domain', models.CharField(blank=True, max_length=255, null=True)),
                ('source_type', models.CharField(blank=True, max_length=50, null=True)),
                ('canonical_url', models.URLField(blank=True, max_length=2000, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='EvidenceSource',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('provider', models.CharField(max_length=50)),
                ('url', models.URLField(blank=True, max_length=2000, null=True)),
                ('canonical_url', models.URLField(blank=True, max_length=2000, null=True)),
                ('title', models.TextField(blank=True, null=True)),
                ('publisher', models.CharField(blank=True, max_length=255, null=True)),
                ('source_type', models.CharField(blank=True, max_length=50, null=True)),
                ('authority_score', models.FloatField(blank=True, null=True)),
                ('content', models.TextField(blank=True, null=True)),
                ('content_hash', models.CharField(blank=True, db_index=True, max_length=64, null=True)),
                ('published_at', models.DateTimeField(blank=True, null=True)),
                ('retrieved_at', models.DateTimeField(auto_now_add=True)),
                ('raw_reference', models.JSONField(blank=True, help_text="Provider-specific identifiers only. Not for general content storage.Example: {'gfc_claim_id': '...', 'tavily_result_index': 2}", null=True)),
                ('canonical_source', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='evidence_sources', to='api.canonicalsource')),
            ],
            options={
                'ordering': ['-retrieved_at'],
            },
        ),
        migrations.CreateModel(
            name='VerificationRun',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('RUNNING', 'Running'), ('COMPLETED', 'Completed'), ('ABSTAINED', 'Abstained'), ('FAILED', 'Failed'), ('CANCELLED', 'Cancelled')], default='PENDING', max_length=20)),
                ('pipeline_version', models.CharField(default='1.0.0', help_text='Version of the verification pipeline used for this run.', max_length=32)),
                ('started_at', models.DateTimeField(blank=True, null=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('failure_stage', models.CharField(blank=True, max_length=100, null=True)),
                ('failure_code', models.CharField(blank=True, max_length=100, null=True)),
                ('failure_message', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('claim', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='verification_runs', to='api.claim')),
                ('triggered_by', models.ForeignKey(blank=True, help_text='User who triggered this verification run, if authenticated.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='verification_runs', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='VerificationEvidence',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('relevance_score', models.FloatField(blank=True, null=True)),
                ('directness_score', models.FloatField(blank=True, null=True)),
                ('recency_score', models.FloatField(blank=True, null=True)),
                ('stance', models.CharField(choices=[('SUPPORTS', 'Supports'), ('REFUTES', 'Refutes'), ('CONTEXT', 'Context'), ('UNKNOWN', 'Unknown')], default='UNKNOWN', max_length=20)),
                ('evidence_role', models.CharField(blank=True, choices=[('PRIMARY', 'Primary Source'), ('SECONDARY', 'Secondary Source'), ('FACT_CHECK', 'Fact Check'), ('CONTEXTUAL', 'Contextual')], max_length=20, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('evidence_source', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='verification_evidence', to='api.evidencesource')),
                ('verification_run', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='evidence', to='api.verificationrun')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddIndex(
            model_name='evidencesource',
            index=models.Index(fields=['provider'], name='evidence_provider_idx'),
        ),
        migrations.AddIndex(
            model_name='evidencesource',
            index=models.Index(fields=['publisher'], name='evidence_publisher_idx'),
        ),
        migrations.AddConstraint(
            model_name='verificationevidence',
            constraint=models.UniqueConstraint(fields=('verification_run', 'evidence_source'), name='unique_evidence_per_verification_run'),
        ),
    ]
