# Generated by Django 5.1.15 on 2026-08-25 19:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0039_canonicalsource_evidencesource_verificationrun_and_more'),
        ('api', '0039_userprofile_email_verification_sent_at'),
    ]

    operations = [
    ]
