# Generated by Django 6.0.2 on 2026-08-29 11:42

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0040_merge_20260826_2246'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='threadflag',
            name='resolved_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.CreateModel(
            name='ModerationCase',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('case_type', models.CharField(choices=[('SAFETY', 'Safety Review'), ('EVIDENCE', 'Evidence Review'), ('ADJUDICATION', 'Verdict Adjudication')], db_index=True, max_length=20)),
                ('status', models.CharField(choices=[('OPEN', 'Open'), ('IN_REVIEW', 'In Review'), ('ESCALATED', 'Escalated'), ('RESOLVED', 'Resolved'), ('REOPENED', 'Reopened'), ('CANCELLED', 'Cancelled')], db_index=True, default='OPEN', max_length=20)),
                ('priority', models.CharField(choices=[('LOW', 'Low'), ('NORMAL', 'Normal'), ('HIGH', 'High'), ('URGENT', 'Urgent')], db_index=True, default='NORMAL', max_length=20)),
                ('source', models.CharField(choices=[('USER_REPORT', 'User Report'), ('EVIDENCE_SUBMISSION', 'Evidence Submission'), ('COMMUNITY_ESCALATION', 'Community Escalation'), ('SYSTEM', 'System Generated'), ('MODERATOR', 'Moderator Created')], default='SYSTEM', max_length=30)),
                ('assigned_at', models.DateTimeField(blank=True, null=True)),
                ('resolution_code', models.CharField(blank=True, max_length=50, null=True)),
                ('resolution_summary', models.TextField(blank=True, null=True)),
                ('resolved_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('assigned_to', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_moderation_cases', to=settings.AUTH_USER_MODEL)),
                ('claim', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='moderation_cases', to='api.claim')),
                ('evidence_submission', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='moderation_cases', to='api.evidencesubmission')),
                ('resolved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='resolved_moderation_cases', to=settings.AUTH_USER_MODEL)),
                ('thread', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='moderation_cases', to='api.thread')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddField(
            model_name='threadflag',
            name='resolution_case',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reports', to='api.moderationcase'),
        ),
        migrations.CreateModel(
            name='ModerationEvent',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('event_type', models.CharField(choices=[('CASE_CREATED', 'Case Created'), ('CASE_CLAIMED', 'Case Claimed'), ('CASE_ASSIGNED', 'Case Assigned'), ('CASE_UNASSIGNED', 'Case Unassigned'), ('REVIEW_STARTED', 'Review Started'), ('CASE_ESCALATED', 'Case Escalated'), ('CASE_RESOLVED', 'Case Resolved'), ('CASE_REOPENED', 'Case Reopened'), ('CASE_CANCELLED', 'Case Cancelled'), ('SAFETY_DISMISSED', 'Safety Report Dismissed'), ('SAFETY_VIOLATION_CONFIRMED', 'Safety Violation Confirmed'), ('CONTENT_REMOVED', 'Content Removed'), ('EVIDENCE_VERIFIED', 'Evidence Verified'), ('EVIDENCE_REJECTED', 'Evidence Rejected'), ('EVIDENCE_REOPENED', 'Evidence Review Reopened'), ('ADJUDICATION_STARTED', 'Adjudication Started'), ('VERDICT_ISSUED', 'Verdict Issued'), ('VERDICT_REOPENED', 'Verdict Reopened'), ('VERDICT_REVISED', 'Verdict Revised'), ('ARTICLE_DRAFT_CREATED', 'Article Draft Created'), ('ARTICLE_SUBMITTED', 'Article Submitted for Review'), ('ARTICLE_PUBLISHED', 'Article Published'), ('ARTICLE_REVISED', 'Article Revised')], db_index=True, max_length=50)),
                ('from_status', models.CharField(blank=True, max_length=20, null=True)),
                ('to_status', models.CharField(blank=True, max_length=20, null=True)),
                ('reason_code', models.CharField(blank=True, max_length=50, null=True)),
                ('notes', models.TextField(blank=True, null=True)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('actor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='moderation_events', to=settings.AUTH_USER_MODEL)),
                ('case', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='events', to='api.moderationcase')),
            ],
            options={
                'ordering': ['created_at'],
            },
        ),
        migrations.AddIndex(
            model_name='moderationcase',
            index=models.Index(fields=['case_type', 'status', '-created_at'], name='mod_case_type_status_idx'),
        ),
        migrations.AddIndex(
            model_name='moderationcase',
            index=models.Index(fields=['assigned_to', 'status'], name='mod_case_assignee_idx'),
        ),
        migrations.AddIndex(
            model_name='moderationcase',
            index=models.Index(fields=['priority', 'status', '-created_at'], name='mod_case_priority_idx'),
        ),
        migrations.AddConstraint(
            model_name='moderationcase',
            constraint=models.UniqueConstraint(condition=models.Q(('case_type', 'SAFETY'), ('status__in', ['OPEN', 'IN_REVIEW', 'ESCALATED', 'REOPENED'])), fields=('thread',), name='uniq_active_safety_case_thread'),
        ),
        migrations.AddConstraint(
            model_name='moderationcase',
            constraint=models.UniqueConstraint(condition=models.Q(('case_type', 'EVIDENCE'), ('status__in', ['OPEN', 'IN_REVIEW', 'ESCALATED', 'REOPENED'])), fields=('evidence_submission',), name='uniq_active_evidence_case'),
        ),
        migrations.AddConstraint(
            model_name='moderationcase',
            constraint=models.UniqueConstraint(condition=models.Q(('case_type', 'ADJUDICATION'), ('status__in', ['OPEN', 'IN_REVIEW', 'ESCALATED', 'REOPENED'])), fields=('claim',), name='uniq_active_adjudication_case'),
        ),
        migrations.AddIndex(
            model_name='moderationevent',
            index=models.Index(fields=['case', 'created_at'], name='mod_event_case_time_idx'),
        ),
        migrations.AddIndex(
            model_name='moderationevent',
            index=models.Index(fields=['event_type', '-created_at'], name='mod_event_type_time_idx'),
        ),
    ]
