# Generated by Django 6.0.2 on 2026-08-29 15:14

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0041_threadflag_resolved_at_moderationcase_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='threadflag',
            name='unique_flag_per_thread_per_user',
        ),
        migrations.AddConstraint(
            model_name='threadflag',
            constraint=models.UniqueConstraint(condition=models.Q(('resolved_at__isnull', True)), fields=('thread', 'flagged_by'), name='unique_active_flag_per_thread_user'),
        ),
    ]
