# Generated by Django 6.0.2 on 2026-08-30 03:02

import django.db.models.deletion
import django.db.models.functions.text
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0043_backfill_safety_moderation_cases'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='OrganizationMembership',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('role', models.CharField(choices=[('OWNER', 'Owner'), ('ADMIN', 'Administrator'), ('LEAD_VERIFIER', 'Lead Verifier'), ('MODERATOR', 'Moderator'), ('RESEARCHER', 'Researcher'), ('CONTRIBUTOR', 'Contributor')], max_length=30)),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('ACTIVE', 'Active'), ('SUSPENDED', 'Suspended'), ('LEFT', 'Left Organization')], db_index=True, default='PENDING', max_length=20)),
                ('joined_at', models.DateTimeField(auto_now_add=True)),
                ('approved_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'ordering': ['organization_id', 'user_id'],
            },
        ),
        migrations.CreateModel(
            name='Organization',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('slug', models.SlugField(max_length=255, unique=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('website', models.URLField(blank=True, max_length=2000, null=True)),
                ('logo_url', models.URLField(blank=True, max_length=2000, null=True)),
                ('organization_type', models.CharField(choices=[('FACT_CHECKING', 'Fact-Checking Organization'), ('NEWS', 'News Organization'), ('UNIVERSITY', 'University'), ('RESEARCH', 'Research Organization'), ('NGO', 'Non-Governmental Organization'), ('GOVERNMENT', 'Government Organization'), ('OTHER', 'Other')], default='OTHER', max_length=30)),
                ('verification_status', models.CharField(choices=[('UNVERIFIED', 'Unverified'), ('PENDING', 'Pending Verification'), ('VERIFIED', 'Verified'), ('REJECTED', 'Rejected')], db_index=True, default='UNVERIFIED', max_length=20)),
                ('partner_status', models.CharField(choices=[('NONE', 'Not a Partner'), ('ACTIVE', 'Active'), ('SUSPENDED', 'Suspended'), ('FORMER', 'Former Partner')], db_index=True, default='NONE', max_length=20)),
                ('expertise_areas', models.JSONField(blank=True, default=list)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['name'],
                'constraints': [models.UniqueConstraint(django.db.models.functions.text.Lower('name'), name='unique_organization_name_ci')],
            },
        ),
        migrations.AddField(
            model_name='moderationcase',
            name='organization',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='moderation_cases', to='api.organization'),
        ),
        migrations.AddIndex(
            model_name='moderationcase',
            index=models.Index(fields=['organization', 'status'], name='mod_case_org_status_idx'),
        ),
        migrations.AddField(
            model_name='organizationmembership',
            name='approved_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='approved_organization_memberships', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='organizationmembership',
            name='organization',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='memberships', to='api.organization'),
        ),
        migrations.AddField(
            model_name='organizationmembership',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='organization_memberships', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddIndex(
            model_name='organizationmembership',
            index=models.Index(fields=['organization', 'status'], name='org_member_org_status_idx'),
        ),
        migrations.AddIndex(
            model_name='organizationmembership',
            index=models.Index(fields=['user', 'status'], name='org_member_user_status_idx'),
        ),
        migrations.AddConstraint(
            model_name='organizationmembership',
            constraint=models.UniqueConstraint(fields=('organization', 'user'), name='unique_user_organization_membership'),
        ),
    ]
