# Generated by Django 6.0.2 on 2026-08-30 04:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0044_organizationmembership_organization_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='evidencesubmission',
            name='rejection_reason',
            field=models.CharField(blank=True, choices=[('IRRELEVANT', 'Irrelevant'), ('UNRELIABLE_SOURCE', 'Unreliable Source'), ('INACCESSIBLE_SOURCE', 'Inaccessible Source'), ('DUPLICATE', 'Duplicate'), ('OUTDATED', 'Outdated'), ('MISREPRESENTS_SOURCE', 'Misrepresents Source'), ('INSUFFICIENT_CONTEXT', 'Insufficient Context'), ('FABRICATED', 'Fabricated'), ('OTHER', 'Other')], max_length=30, null=True),
        ),
    ]
