# Generated by Django 6.0.2 on 2026-08-30 07:03

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0046_backfill_evidence_moderation_cases'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AdjudicationDecision',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('verdict', models.CharField(choices=[('FACT', 'Fact'), ('FAKE', 'Fake'), ('MISLEADING', 'Misleading'), ('SATIRE', 'Satire'), ('UNVERIFIED', 'Unverified')], max_length=20)),
                ('canonical_claim', models.TextField(blank=True)),
                ('rationale', models.TextField(blank=True)),
                ('ai_verdict_snapshot', models.CharField(blank=True, max_length=20, null=True)),
                ('ai_confidence_snapshot', models.FloatField(blank=True, null=True)),
                ('ai_summary_snapshot', models.TextField(blank=True, null=True)),
                ('ai_pipeline_version_snapshot', models.CharField(blank=True, max_length=32, null=True)),
                ('decision_source', models.CharField(choices=[('HUMAN_REVIEW', 'Human Review'), ('LEGACY_MIGRATION', 'Legacy Migration')], default='HUMAN_REVIEW', max_length=30)),
                ('revision_number', models.PositiveIntegerField(default=1)),
                ('is_current', models.BooleanField(db_index=True, default=True)),
                ('decided_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('claim', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='adjudication_decisions', to='api.claim')),
                ('decided_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='adjudication_decisions', to=settings.AUTH_USER_MODEL)),
                ('moderation_case', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='adjudication_decisions', to='api.moderationcase')),
                ('organization', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='adjudication_decisions', to='api.organization')),
                ('supersedes', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='superseded_by', to='api.adjudicationdecision')),
                ('verification_run', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='adjudication_decisions', to='api.verificationrun')),
            ],
            options={
                'ordering': ['-decided_at'],
                'indexes': [models.Index(fields=['claim', 'is_current'], name='adj_dec_claim_current_idx'), models.Index(fields=['organization', '-decided_at'], name='adj_dec_org_time_idx')],
                'constraints': [models.UniqueConstraint(condition=models.Q(('is_current', True)), fields=('claim',), name='uniq_current_adjudication_decision_claim'), models.UniqueConstraint(fields=('claim', 'revision_number'), name='uniq_adjudication_claim_revision')],
            },
        ),
    ]
