# Generated by Django 6.0.2 on 2026-08-31 14:38

import django.contrib.postgres.search
import django.db.models.deletion
import pgvector.django.vector
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0048_backfill_adjudication_decisions'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='OfficialFactCheckSource',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('url', models.URLField(max_length=2000)),
                ('title', models.TextField(blank=True, null=True)),
                ('source_type', models.CharField(choices=[('VERIFIED_EVIDENCE', 'Verified Community Evidence'), ('MODERATOR_ADDED', 'Moderator Added'), ('LEGACY_IMPORT', 'Legacy Import')], default='MODERATOR_ADDED', max_length=30)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['created_at'],
            },
        ),
        migrations.AlterModelOptions(
            name='officialfactcheck',
            options={'ordering': ['-published_at', '-created_at']},
        ),
        migrations.AddField(
            model_name='officialfactcheck',
            name='adjudication_decision',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='official_fact_checks', to='api.adjudicationdecision'),
        ),
        migrations.AddField(
            model_name='officialfactcheck',
            name='archived_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='officialfactcheck',
            name='article_body',
            field=models.TextField(blank=True, help_text='Full public-facing fact-check analysis.'),
        ),
        migrations.AddField(
            model_name='officialfactcheck',
            name='claim',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='official_fact_checks', to='api.claim'),
        ),
        migrations.AddField(
            model_name='officialfactcheck',
            name='drafted_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='drafted_fact_checks', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='officialfactcheck',
            name='headline',
            field=models.CharField(blank=True, max_length=300),
        ),
        migrations.AddField(
            model_name='officialfactcheck',
            name='organization',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='official_fact_checks', to='api.organization'),
        ),
        migrations.AddField(
            model_name='officialfactcheck',
            name='publication_status',
            field=models.CharField(choices=[('DRAFT', 'Draft'), ('IN_REVIEW', 'In Review'), ('PUBLISHED', 'Published'), ('ARCHIVED', 'Archived')], db_index=True, default='DRAFT', max_length=20),
        ),
        migrations.AddField(
            model_name='officialfactcheck',
            name='published_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='officialfactcheck',
            name='reviewed_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='officialfactcheck',
            name='reviewed_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reviewed_fact_checks', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='officialfactcheck',
            name='submitted_for_review_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='officialfactcheck',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='officialfactcheck',
            name='version',
            field=models.PositiveIntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='officialfactcheck',
            name='canonical_claim',
            field=models.TextField(help_text='The authoritative canonical claim from the adjudication decision.'),
        ),
        migrations.AlterField(
            model_name='officialfactcheck',
            name='embedding',
            field=pgvector.django.vector.VectorField(blank=True, dimensions=384, help_text='Sentence-transformer embedding for semantic search.', null=True),
        ),
        migrations.AlterField(
            model_name='officialfactcheck',
            name='published_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='published_fact_checks', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='officialfactcheck',
            name='search_vector',
            field=django.contrib.postgres.search.SearchVectorField(blank=True, help_text='PostgreSQL full-text search vector.', null=True),
        ),
        migrations.AlterField(
            model_name='officialfactcheck',
            name='source_thread',
            field=models.ForeignKey(blank=True, help_text='Legacy link to the community thread that produced this fact-check.', null=True, on_delete=django.db.models.deletion.SET_NULL, to='api.thread'),
        ),
        migrations.AlterField(
            model_name='officialfactcheck',
            name='sources',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AlterField(
            model_name='officialfactcheck',
            name='summary',
            field=models.TextField(help_text='Concise public-facing summary of the fact-check.'),
        ),
        migrations.AlterField(
            model_name='officialfactcheck',
            name='verdict',
            field=models.CharField(choices=[('FACT', 'Fact'), ('FAKE', 'Fake'), ('MISLEADING', 'Misleading'), ('SATIRE', 'Satire'), ('UNVERIFIED', 'Unverified')], max_length=20),
        ),
        migrations.AddIndex(
            model_name='officialfactcheck',
            index=models.Index(fields=['publication_status', '-published_at'], name='factcheck_status_published_idx'),
        ),
        migrations.AddIndex(
            model_name='officialfactcheck',
            index=models.Index(fields=['organization', 'publication_status'], name='factcheck_org_status_idx'),
        ),
        migrations.AddConstraint(
            model_name='officialfactcheck',
            constraint=models.UniqueConstraint(condition=models.Q(('claim__isnull', False)), fields=('claim', 'version'), name='uniq_fact_check_claim_version'),
        ),
        migrations.AddConstraint(
            model_name='officialfactcheck',
            constraint=models.UniqueConstraint(condition=models.Q(('claim__isnull', False), ('publication_status', 'PUBLISHED')), fields=('claim',), name='uniq_published_fact_check_claim'),
        ),
        migrations.AddField(
            model_name='officialfactchecksource',
            name='added_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='added_fact_check_sources', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='officialfactchecksource',
            name='evidence_submission',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='official_fact_check_sources', to='api.evidencesubmission'),
        ),
        migrations.AddField(
            model_name='officialfactchecksource',
            name='fact_check',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='source_items', to='api.officialfactcheck'),
        ),
        migrations.AddIndex(
            model_name='officialfactchecksource',
            index=models.Index(fields=['fact_check', 'source_type'], name='factcheck_source_type_idx'),
        ),
        migrations.AddConstraint(
            model_name='officialfactchecksource',
            constraint=models.UniqueConstraint(fields=('fact_check', 'url'), name='unique_fact_check_source_url'),
        ),
    ]
