# Generated by Django 6.0.2 on 2026-09-01 15:41

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0050_backfill_fact_check_publication'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='KnowledgeReuseEvent',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('reuse_type', models.CharField(choices=[('USER_RESPONSE', 'User-Facing Reuse'), ('VERIFICATION_CONTEXT', 'Verification Context Reuse')], db_index=True, max_length=30)),
                ('match_method', models.CharField(choices=[('EXACT_TEXT', 'Exact Text Match'), ('SEMANTIC', 'Semantic Match'), ('FULL_TEXT', 'Full-Text Match'), ('CLAIM_CACHE', 'Claim Cache Match')], db_index=True, max_length=30)),
                ('similarity_score', models.FloatField(blank=True, null=True)),
                ('query_fingerprint', models.CharField(blank=True, db_index=True, max_length=64, null=True)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('fact_check', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='reuse_events', to='api.officialfactcheck')),
                ('target_claim', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='knowledge_reuse_events', to='api.claim')),
                ('triggered_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='knowledge_reuse_events', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['fact_check', 'reuse_type', '-created_at'], name='reuse_fact_type_time_idx'), models.Index(fields=['target_claim', '-created_at'], name='reuse_target_time_idx'), models.Index(fields=['match_method', '-created_at'], name='reuse_method_time_idx')],
            },
        ),
    ]
