# Generated by Django 6.0.2 on 2026-09-02 10:14

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0051_knowledgereuseevent'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='VerificationAssignment',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('status', models.CharField(choices=[('AVAILABLE', 'Available'), ('ACTIVE', 'Active'), ('RELEASED', 'Released'), ('COMPLETED', 'Completed')], db_index=True, default='AVAILABLE', max_length=20)),
                ('claimed_at', models.DateTimeField(blank=True, null=True)),
                ('released_at', models.DateTimeField(blank=True, null=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('claim', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='verification_assignments', to='api.claim')),
                ('claimed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='claimed_verification_assignments', to=settings.AUTH_USER_MODEL)),
                ('organization', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='verification_assignments', to='api.organization')),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['status', '-created_at'], name='verify_assign_status_idx'), models.Index(fields=['organization', 'status'], name='verify_assign_org_idx')],
                'constraints': [models.UniqueConstraint(condition=models.Q(('status__in', ['AVAILABLE', 'ACTIVE'])), fields=('claim',), name='unique_open_verification_assignment_per_claim')],
            },
        ),
    ]
