# Generated by Django 6.0.2 on 2026-09-05 16:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0054_organizationinvitation'),
    ]

    operations = [
        migrations.AddField(
            model_name='organization',
            name='public_logo_enabled',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='organization',
            name='public_profile_enabled',
            field=models.BooleanField(default=False),
        ),
    ]
