# Generated by Django 6.0.2 on 2026-09-08

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0055_organization_public_logo_enabled_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="AdjudicationDecisionEvidenceSnapshot",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("claim_id", models.UUIDField(editable=False)),
                (
                    "schema_version",
                    models.PositiveSmallIntegerField(default=1, editable=False),
                ),
                (
                    "captured_at",
                    models.DateTimeField(auto_now_add=True, editable=False),
                ),
                (
                    "evidence_records",
                    models.JSONField(default=list, editable=False),
                ),
                (
                    "decision",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="evidence_snapshot",
                        to="api.adjudicationdecision",
                    ),
                ),
            ],
            options={
                "ordering": ["-captured_at"],
            },
        ),
    ]
