# Generated by Django 6.0.2 on 2026-09-09

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0056_adjudicationdecisionevidencesnapshot"),
    ]

    operations = [
        migrations.AddField(
            model_name="officialfactchecksource",
            name="is_editorially_selected",
            field=models.BooleanField(
                blank=True,
                default=None,
                help_text=(
                    "Whether an editor explicitly selected this source. Null "
                    "preserves unknown provenance for records created before this "
                    "field existed."
                ),
                null=True,
            ),
        ),
        migrations.CreateModel(
            name="OfficialFactCheckSourceEvidenceLink",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("captured_evidence_id", models.UUIDField(editable=False)),
                (
                    "snapshot",
                    models.ForeignKey(
                        editable=False,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="source_links",
                        to="api.adjudicationdecisionevidencesnapshot",
                    ),
                ),
                (
                    "source",
                    models.ForeignKey(
                        editable=False,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="evidence_links",
                        to="api.officialfactchecksource",
                    ),
                ),
            ],
            options={
                "ordering": ["source_id", "captured_evidence_id", "id"],
                "constraints": [
                    models.UniqueConstraint(
                        fields=("source", "captured_evidence_id"),
                        name="unique_source_captured_evidence",
                    )
                ],
            },
        ),
    ]
