# Generated by Django 6.0.2 on 2026-09-09

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0057_officialfactchecksource_lineage"),
    ]

    operations = [
        migrations.CreateModel(
            name="OfficialFactCheckPublicationSnapshot",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "schema_version",
                    models.PositiveSmallIntegerField(default=1, editable=False),
                ),
                ("captured_at", models.DateTimeField(editable=False)),
                ("payload", models.JSONField(default=dict, editable=False)),
                (
                    "decision_snapshot",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="publication_snapshots",
                        to="api.adjudicationdecisionevidencesnapshot",
                    ),
                ),
                (
                    "fact_check",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="publication_snapshot",
                        to="api.officialfactcheck",
                    ),
                ),
            ],
            options={
                "ordering": ["-captured_at", "id"],
            },
        ),
    ]
