# Generated by Django 6.0.2 on 2026-09-09

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0058_officialfactcheckpublicationsnapshot"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="officialfactcheck",
            name="revision_kind",
            field=models.CharField(
                blank=True,
                choices=[
                    ("INITIAL", "Initial"),
                    ("EDITORIAL_REVISION", "Editorial revision"),
                    ("FACTUAL_CORRECTION", "Factual correction"),
                ],
                max_length=24,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="officialfactcheck",
            name="revision_reason",
            field=models.TextField(blank=True, max_length=2000, null=True),
        ),
        migrations.AddField(
            model_name="officialfactcheck",
            name="revision_requested_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="officialfactcheck",
            name="revision_requested_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="requested_fact_check_revisions",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="officialfactcheck",
            name="supersedes",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="successors",
                to="api.officialfactcheck",
            ),
        ),
        migrations.AddConstraint(
            model_name="officialfactcheck",
            constraint=models.UniqueConstraint(
                condition=models.Q(
                    ("publication_status__in", ("DRAFT", "IN_REVIEW", "PUBLISHED")),
                    ("supersedes__isnull", False),
                ),
                fields=("supersedes",),
                name="uniq_active_fact_check_successor",
            ),
        ),
        migrations.AddConstraint(
            model_name="officialfactcheck",
            constraint=models.CheckConstraint(
                condition=(
                    models.Q(
                        ("revision_kind__isnull", True),
                        ("revision_reason__isnull", True),
                        ("revision_requested_at__isnull", True),
                        ("revision_requested_by__isnull", True),
                        ("supersedes__isnull", True),
                    )
                    | models.Q(
                        ("revision_kind", "INITIAL"),
                        ("revision_reason__isnull", True),
                        ("revision_requested_at__isnull", True),
                        ("revision_requested_by__isnull", True),
                        ("supersedes__isnull", True),
                    )
                    | models.Q(
                        (
                            "revision_kind__in",
                            ("EDITORIAL_REVISION", "FACTUAL_CORRECTION"),
                        ),
                        ("revision_reason__isnull", False),
                        ("revision_requested_at__isnull", False),
                        ("supersedes__isnull", False),
                    )
                ),
                name="fact_check_revision_metadata_shape",
            ),
        ),
    ]
