# Generated by Django 6.0.2 on 2026-09-09 04:59

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0059_officialfactcheck_revision_metadata'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='officialfactcheck',
            name='uniq_active_fact_check_successor',
        ),
        migrations.AddConstraint(
            model_name='officialfactcheck',
            constraint=models.UniqueConstraint(condition=models.Q(('supersedes__isnull', False), models.Q(('publication_status__in', ('DRAFT', 'IN_REVIEW', 'PUBLISHED')), ('published_at__isnull', False), _connector='OR')), fields=('supersedes',), name='uniq_reserved_fact_check_successor'),
        ),
    ]
