# Generated by Django 6.0.2 on 2026-09-09

import uuid

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0060_reserve_published_successor_history"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name="moderationevent",
            name="event_type",
            field=models.CharField(
                choices=[
                    ("CASE_CREATED", "Case Created"),
                    ("CASE_CLAIMED", "Case Claimed"),
                    ("CASE_ASSIGNED", "Case Assigned"),
                    ("CASE_UNASSIGNED", "Case Unassigned"),
                    ("REVIEW_STARTED", "Review Started"),
                    ("CASE_ESCALATED", "Case Escalated"),
                    ("CASE_RESOLVED", "Case Resolved"),
                    ("CASE_REOPENED", "Case Reopened"),
                    ("CASE_CANCELLED", "Case Cancelled"),
                    ("SAFETY_DISMISSED", "Safety Report Dismissed"),
                    (
                        "SAFETY_VIOLATION_CONFIRMED",
                        "Safety Violation Confirmed",
                    ),
                    ("CONTENT_REMOVED", "Content Removed"),
                    ("EVIDENCE_VERIFIED", "Evidence Verified"),
                    ("EVIDENCE_REJECTED", "Evidence Rejected"),
                    ("EVIDENCE_REOPENED", "Evidence Review Reopened"),
                    ("ADJUDICATION_STARTED", "Adjudication Started"),
                    ("VERDICT_ISSUED", "Verdict Issued"),
                    ("VERDICT_REOPENED", "Verdict Reopened"),
                    ("VERDICT_REVISED", "Verdict Revised"),
                    ("ARTICLE_DRAFT_CREATED", "Article Draft Created"),
                    ("ARTICLE_SUBMITTED", "Article Submitted for Review"),
                    ("ARTICLE_PUBLISHED", "Article Published"),
                    ("ARTICLE_REVISED", "Article Revised"),
                    (
                        "FACTUAL_CORRECTION_REQUESTED",
                        "Factual Correction Requested",
                    ),
                ],
                db_index=True,
                max_length=50,
            ),
        ),
        migrations.CreateModel(
            name="FactualCorrectionRequest",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("requested_by_snapshot", models.JSONField(editable=False)),
                ("organization_snapshot", models.JSONField(editable=False)),
                ("correction_reason", models.TextField(max_length=2000)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("ACTIVE", "Active"),
                            ("COMPLETED", "Completed"),
                            ("CANCELLED", "Cancelled"),
                        ],
                        db_index=True,
                        default="ACTIVE",
                        max_length=20,
                    ),
                ),
                (
                    "requested_at",
                    models.DateTimeField(
                        default=django.utils.timezone.now,
                        editable=False,
                    ),
                ),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "claim",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="factual_correction_requests",
                        to="api.claim",
                    ),
                ),
                (
                    "moderation_case",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="factual_correction_request",
                        to="api.moderationcase",
                    ),
                ),
                (
                    "organization",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="factual_correction_requests",
                        to="api.organization",
                    ),
                ),
                (
                    "predecessor_decision",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="factual_correction_requests",
                        to="api.adjudicationdecision",
                    ),
                ),
                (
                    "predecessor_fact_check",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="factual_correction_requests",
                        to="api.officialfactcheck",
                    ),
                ),
                (
                    "predecessor_publication_snapshot",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="factual_correction_requests",
                        to="api.officialfactcheckpublicationsnapshot",
                    ),
                ),
                (
                    "requested_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="factual_correction_requests",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-requested_at", "id"],
                "indexes": [
                    models.Index(
                        fields=["organization", "status"],
                        name="fact_correction_org_status_idx",
                    )
                ],
                "constraints": [
                    models.UniqueConstraint(
                        condition=models.Q(("status", "ACTIVE")),
                        fields=("claim",),
                        name="uniq_active_factual_correction_request",
                    )
                ],
            },
        ),
    ]
