# Generated by Django 5.1.15 on 2026-09-17 16:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0062_factualcorrectionproposal'),
    ]

    operations = [
        migrations.AddField(
            model_name='verificationevidence',
            name='retrieval_provenance',
            field=models.JSONField(blank=True, default=list),
        ),
    ]
