# Generated by Django 6.0.2 on 2026-09-16 16:47

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0066_knowledgereuseevent_attribution_snapshots'),
    ]

    operations = [
        migrations.CreateModel(
            name='ClaimFactCheckReference',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('relationship_kind', models.CharField(choices=[('AUTHORITATIVE', 'Authoritative'), ('RELATED', 'Related')], max_length=20)),
                ('match_method', models.CharField(choices=[('EXACT_CANONICAL', 'Exact canonical'), ('EXACT_HEADLINE', 'Exact headline'), ('SEMANTIC', 'Semantic'), ('FULL_TEXT', 'Full text')], max_length=20)),
                ('similarity_score', models.FloatField(blank=True, null=True)),
                ('query_fingerprint', models.CharField(max_length=64)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('fact_check', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='claim_references', to='api.officialfactcheck')),
                ('target_claim', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fact_check_references', to='api.claim')),
            ],
            options={
                'constraints': [models.UniqueConstraint(condition=models.Q(('relationship_kind', 'AUTHORITATIVE')), fields=('target_claim',), name='uniq_authoritative_claim_reference'), models.CheckConstraint(condition=models.Q(('query_fingerprint__regex', '^[0-9a-f]{64}$')), name='claim_reference_sha256_only')],
            },
        ),
    ]
