# Generated by Django 6.0.2 on 2026-09-17 02:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0067_claimfactcheckreference'),
    ]

    operations = [
        migrations.AlterField(
            model_name='claimfactcheckreference',
            name='match_method',
            field=models.CharField(choices=[('EXACT_CANONICAL', 'Exact canonical'), ('EQUIVALENT_CLAIM', 'Equivalent claim'), ('EXACT_HEADLINE', 'Exact headline'), ('SEMANTIC', 'Semantic'), ('FULL_TEXT', 'Full text')], max_length=20),
        ),
    ]
