# Generated by Django 6.0.2 on 2026-09-17 15:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0068_claim_reference_equivalent_claim'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='claimfactcheckreference',
            constraint=models.UniqueConstraint(fields=('target_claim', 'fact_check', 'relationship_kind'), name='uniq_claim_fact_check_relationship'),
        ),
    ]
