# Generated by Django 5.1.15 on 2026-09-17 18:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0063_verificationevidence_retrieval_provenance'),
        ('api', '0069_claim_fact_check_relationship_unique'),
    ]

    operations = [
    ]
