# Generated by Django 5.1.15 on 2026-09-19 03:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0070_merge_20260918_0225'),
        ('api', '0070_public_reach_event'),
    ]

    operations = [
    ]
