# Generated by Django 5.1.15 on 2026-09-22 17:04

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0071_merge_20260919_1124'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('notification_type', models.CharField(choices=[('AUTOMATED_VERIFICATION_COMPLETED', 'Analysis completed'), ('AUTOMATED_VERIFICATION_FAILED', 'Analysis failed'), ('PARTNER_FACT_CHECK_PUBLISHED', 'Partner fact-check published'), ('PARTNER_FACT_CHECK_CORRECTED', 'Partner fact-check corrected'), ('ARTICLE_RETURNED_FOR_REWORK', 'Article returned for rework'), ('FACT_CHECK_PUBLISHED', 'Fact-check published'), ('FACTUAL_CORRECTION_PUBLISHED', 'Factual correction published'), ('ORGANIZATION_MEMBERSHIP_CHANGED', 'Membership changed'), ('THREAD_COMMENTED', 'Thread commented'), ('EVIDENCE_REVIEWED', 'Evidence reviewed')], max_length=40)),
                ('target_type', models.CharField(choices=[('CLAIM', 'Claim'), ('THREAD', 'Thread'), ('OFFICIAL_FACT_CHECK', 'Official fact-check'), ('WORKSPACE', 'Workspace'), ('ORGANIZATION', 'Organization')], max_length=24)),
                ('target_id', models.UUIDField(blank=True, null=True)),
                ('title', models.CharField(max_length=180)),
                ('message', models.CharField(max_length=500)),
                ('dedupe_key', models.CharField(max_length=200)),
                ('read_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('actor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='acted_notifications', to=settings.AUTH_USER_MODEL)),
                ('organization', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='notifications', to='api.organization')),
                ('recipient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at', '-id'],
                'indexes': [models.Index(fields=['recipient', '-created_at', '-id'], name='notification_inbox_idx'), models.Index(condition=models.Q(('read_at__isnull', True)), fields=['recipient', '-created_at'], name='notification_unread_idx')],
                'constraints': [models.UniqueConstraint(fields=('recipient', 'dedupe_key'), name='notification_recipient_event_uniq'), models.CheckConstraint(condition=models.Q(('notification_type__in', ['AUTOMATED_VERIFICATION_COMPLETED', 'AUTOMATED_VERIFICATION_FAILED', 'PARTNER_FACT_CHECK_PUBLISHED', 'PARTNER_FACT_CHECK_CORRECTED', 'ARTICLE_RETURNED_FOR_REWORK', 'FACT_CHECK_PUBLISHED', 'FACTUAL_CORRECTION_PUBLISHED', 'ORGANIZATION_MEMBERSHIP_CHANGED', 'THREAD_COMMENTED', 'EVIDENCE_REVIEWED'])), name='notification_type_valid'), models.CheckConstraint(condition=models.Q(('target_type__in', ['CLAIM', 'THREAD', 'OFFICIAL_FACT_CHECK', 'WORKSPACE', 'ORGANIZATION'])), name='notification_target_valid')],
            },
        ),
    ]
