# Generated by Django 5.1.15 on 2026-09-26 04:33

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0073_thread_comment_replies_and_likes'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='notification',
            name='notification_type_valid',
        ),
        migrations.RemoveConstraint(
            model_name='notification',
            name='notification_target_valid',
        ),
        migrations.AlterField(
            model_name='notification',
            name='notification_type',
            field=models.CharField(choices=[('AUTOMATED_VERIFICATION_COMPLETED', 'Analysis completed'), ('AUTOMATED_VERIFICATION_FAILED', 'Analysis failed'), ('PARTNER_FACT_CHECK_PUBLISHED', 'Partner fact-check published'), ('PARTNER_FACT_CHECK_CORRECTED', 'Partner fact-check corrected'), ('ARTICLE_RETURNED_FOR_REWORK', 'Article returned for rework'), ('FACT_CHECK_PUBLISHED', 'Fact-check published'), ('FACTUAL_CORRECTION_PUBLISHED', 'Factual correction published'), ('ORGANIZATION_MEMBERSHIP_CHANGED', 'Membership changed'), ('THREAD_COMMENTED', 'Thread commented'), ('EVIDENCE_REVIEWED', 'Evidence reviewed'), ('USER_FOLLOWED', 'User followed')], max_length=40),
        ),
        migrations.AlterField(
            model_name='notification',
            name='target_type',
            field=models.CharField(choices=[('CLAIM', 'Claim'), ('THREAD', 'Thread'), ('OFFICIAL_FACT_CHECK', 'Official fact-check'), ('WORKSPACE', 'Workspace'), ('ORGANIZATION', 'Organization'), ('USER_PROFILE', 'User profile')], max_length=24),
        ),
        migrations.AddConstraint(
            model_name='notification',
            constraint=models.CheckConstraint(condition=models.Q(('notification_type__in', ['AUTOMATED_VERIFICATION_COMPLETED', 'AUTOMATED_VERIFICATION_FAILED', 'PARTNER_FACT_CHECK_PUBLISHED', 'PARTNER_FACT_CHECK_CORRECTED', 'ARTICLE_RETURNED_FOR_REWORK', 'FACT_CHECK_PUBLISHED', 'FACTUAL_CORRECTION_PUBLISHED', 'ORGANIZATION_MEMBERSHIP_CHANGED', 'THREAD_COMMENTED', 'EVIDENCE_REVIEWED', 'USER_FOLLOWED'])), name='notification_type_valid'),
        ),
        migrations.AddConstraint(
            model_name='notification',
            constraint=models.CheckConstraint(condition=models.Q(('target_type__in', ['CLAIM', 'THREAD', 'OFFICIAL_FACT_CHECK', 'WORKSPACE', 'ORGANIZATION', 'USER_PROFILE'])), name='notification_target_valid'),
        ),
    ]
