# Generated by Django 5.1.15 on 2026-09-26 17:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0074_alter_thread_escalation_reason'),
        ('api', '0074_notification_user_followed'),
    ]

    operations = [
    ]
