# Generated by Django 6.0.2 on 2026-09-27 18:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0075_merge_20260927_0112'),
    ]

    operations = [
        migrations.AddField(
            model_name='claim',
            name='analyzed_claim',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='claim',
            name='source_context',
            field=models.TextField(blank=True, null=True),
        ),
    ]
