# Generated by Django 6.0.2 on 2026-10-02 13:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0075_merge_20260927_0112'),
    ]

    operations = [
        migrations.AddField(
            model_name='verificationrun',
            name='abstention_reason',
            field=models.CharField(blank=True, choices=[('OUT_OF_SCOPE', 'Out of scope')], max_length=50, null=True),
        ),
    ]
